build.gradle, src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java
- #관련 이슈 번호
- build.gradle 빌드하고 시작해주세요
=> [FEAT] build.gradle 의존성 추가, 실시간 방송 RestController 추가

build.gradle, src/main/java/susussg/pengreenlive/dashboard/Controller/CategoryController.java, src/main/java/susussg/pengreenlive/dashboard/DTO/BroadcastCategoryDTO.java, src/main/java/susussg/pengreenlive/dashboard/DTO/CategoryDTO.java, src/main/java/susussg/pengreenlive/dashboard/Mapper/CategoryMapper.java, src/main/java/susussg/pengreenlive/dashboard/Service/CategorySerivceImpl.java, src/main/java/susussg/pengreenlive/dashboard/Service/CategoryService.java, src/main/resources/mappers/CategoryMapper.xml, src/test/java/susussg/pengreenlive/service/CategoryServiceTest.java
=> [FEAT] 상품, 방송 카테고리 목록 조회

src/main/java/susussg/pengreenlive/dashboard/Controller/ShopInfoController.java, src/main/java/susussg/pengreenlive/dashboard/DTO/ShopInfoDTO.java, src/main/java/susussg/pengreenlive/dashboard/Mapper/ShopInfoMapper.java, src/main/java/susussg/pengreenlive/dashboard/Service/ShopInfoService.java, src/main/java/susussg/pengreenlive/dashboard/Service/ShopInfoServiceImpl.java, src/main/resources/mappers/ShopInfoMapper.xml, src/test/java/susussg/pengreenlive/service/ShopInfoServiceTest.java
=> [FEAT] 상점 정보 등록 기능 구현

src/main/java/susussg/pengreenlive/chat/config/WebSocketBrokerConfiguration.java
=> [FIX] 테스트 데이터 삽입 로직 비활성화 처리

.github/workflows/gradle.yml
=> [FILE] :  gradle.yml 추가

src/main/java/susussg/pengreenlive/config/CorsConfig.java, src/main/java/susussg/pengreenlive/dashboard/Controller/ShopInfoController.java, src/main/java/susussg/pengreenlive/dashboard/DTO/ProductDTO.java, src/main/java/susussg/pengreenlive/dashboard/Mapper/ProductMapper.java, src/main/java/susussg/pengreenlive/dashboard/Mapper/ShopInfoMapper.java, src/main/java/susussg/pengreenlive/dashboard/Service/CategoryServiceImpl.java, src/main/java/susussg/pengreenlive/dashboard/Service/ProductService.java, src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java, src/main/java/susussg/pengreenlive/dashboard/Service/ShopInfoService.java, src/main/java/susussg/pengreenlive/dashboard/Service/ShopInfoServiceImpl.java, src/main/resources/mappers/ProductMapper.xml, src/main/resources/mappers/ShopInfoMapper.xml, src/test/java/susussg/pengreenlive/service/ProductServiceTest.java, src/test/java/susussg/pengreenlive/service/ShopInfoServiceTest.java
=> [FEAT] 상점정보 조회 및 수정 기능 구현

src/main/java/susussg/pengreenlive/chat/controller/ChatController.java, src/main/java/susussg/pengreenlive/chat/handler/BrokerController.java
=> [FEAT] 한줄공지 메소드 추가

src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java
=> [FEAT] 상품 목록 조회 구현

build.gradle, src/main/java/susussg/pengreenlive/config/SchedulerConfig.java, src/main/java/susussg/pengreenlive/util/DTO/BanwordDTO.java, src/main/java/susussg/pengreenlive/util/DTO/BanwordValidationResultDTO.java, src/main/java/susussg/pengreenlive/util/DTO/ForbiddenWordDTO.java, src/main/java/susussg/pengreenlive/util/Mapper/ForbiddenWordMapper.java, src/main/java/susussg/pengreenlive/util/Service/BanwordService.java, src/main/java/susussg/pengreenlive/util/Service/ForbiddenWordService.java, src/main/java/susussg/pengreenlive/util/Service/ForbiddenWordServiceImpl.java, src/main/resources/mappers/ForbiddenWordMapper.xml, src/test/java/susussg/pengreenlive/service/BanwordServiceTest.java, src/test/java/susussg/pengreenlive/service/ForbiddenWordTest.java
=> [FEAT] 금칙어 필터링 백엔드 서비스

src/main/java/susussg/pengreenlive/config/CorsConfig.java
=> [FIX] CORS 충돌 수정

src/main/java/susussg/pengreenlive/chat/handler/BrokerController.java, src/main/java/susussg/pengreenlive/chat/handler/MyHandler.java
=> [FEAT] 비속어 필터링 채팅 연결

src/main/java/susussg/pengreenlive/chat/handler/BrokerController.java
=> [FIX] 입,퇴장 메시지 비활성화 수정

src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java, src/main/java/susussg/pengreenlive/dashboard/Controller/ShopInfoController.java, src/main/java/susussg/pengreenlive/dashboard/DTO/ProductDTO.java, src/main/java/susussg/pengreenlive/dashboard/Mapper/ProductMapper.java, src/main/java/susussg/pengreenlive/dashboard/Service/ProductService.java, src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java, src/main/resources/mappers/ProductMapper.xml, src/test/java/susussg/pengreenlive/service/ProductServiceTest.java
- #관련 이슈 번호
> 환경인증 API 추후 연동 예정
- 특이사항1
- 특이사항2
=> [FEAT] 상품 등록 기능 구현

src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java, src/main/java/susussg/pengreenlive/dashboard/Mapper/ProductMapper.java, src/main/java/susussg/pengreenlive/dashboard/Service/ProductService.java, src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java, src/main/resources/mappers/ProductMapper.xml, src/test/java/susussg/pengreenlive/service/ProductServiceTest.java
- #관련 이슈 번호
- 판매자별 아닌 전체 상품 목록 조회 기능은 확인이 필요할 수 있을것 같아 삭제하지 않고 두었습니다. 
추후 불필요시 삭제 예정.
=> [REFACTOR] 각 판매자별 상품 목록 조회로 수정

build.gradle, src/main/java/susussg/pengreenlive/config/ModelConfig.java, src/main/java/susussg/pengreenlive/order/OrderController.java, src/main/java/susussg/pengreenlive/order/OrderRepository.java, src/main/java/susussg/pengreenlive/order/domain/Order.java, src/main/java/susussg/pengreenlive/order/dto/OrderFormDTO.java, src/main/java/susussg/pengreenlive/order/service/OrderService.java, src/main/java/susussg/pengreenlive/payment/PaymentController.java, src/main/java/susussg/pengreenlive/payment/dto/PaymentInitiateRequestDTO.java, src/main/java/susussg/pengreenlive/payment/dto/verifyPaymentDTO.java, src/main/java/susussg/pengreenlive/payment/service/PaymentService.java
=> [FEAT] 상품 주문 API 및 결제 승인 API 구현

src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java
=> [FEAT] 현재 시청자수 확인 기능 추가

src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java, src/main/java/susussg/pengreenlive/dashboard/DTO/ProductDTO.java, src/main/java/susussg/pengreenlive/dashboard/Mapper/ProductMapper.java, src/main/java/susussg/pengreenlive/dashboard/Service/ProductService.java, src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java, src/main/resources/mappers/ProductMapper.xml, src/test/java/susussg/pengreenlive/service/ProductServiceTest.java
- #관련 이슈 번호
- 친환경 인증 API 추후 연결 예정
=> [REFACTOR] 상품 이미지 및 등록 기능 수정

src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastStatisticsController.java, src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastStatistics.java, src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapper.java, src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsService.java, src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceImpl.java, src/main/resources/mappers/BroadcastStatisticsMapper.xml, src/test/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapperTest.java, src/test/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceTest.java
- #관련 이슈 번호
- Service 레이어까지 테스트코드 완료
=> [FEAT] : 방송 통계 생성, 방송 통계 조회, 좋아요 증감, 평균 시청자수 최대 시청자수 업데이트 기능 추가

src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java, src/main/java/susussg/pengreenlive/dashboard/Mapper/ProductMapper.java, src/main/java/susussg/pengreenlive/dashboard/Service/ProductService.java, src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java, src/main/resources/mappers/ProductMapper.xml, src/test/java/susussg/pengreenlive/service/ProductServiceTest.java
- #관련 이슈 번호
- 친환경 인증 API 추후 연결 예정
=> [FEAT] 상품 정보 수정 기능 구현

src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java, src/main/java/susussg/pengreenlive/dashboard/Mapper/ProductMapper.java, src/main/java/susussg/pengreenlive/dashboard/Service/ProductService.java, src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java, src/main/resources/mappers/ProductMapper.xml, src/test/java/susussg/pengreenlive/service/ProductServiceTest.java
=> [FEAT] 채널 판매 상품 삭제 기능 구현

build.gradle, src/main/java/susussg/pengreenlive/config/RedisConfig.java, src/main/java/susussg/pengreenlive/payment/PaymentController.java, src/main/java/susussg/pengreenlive/payment/dto/verifyPaymentDTO.java
- 레디스 세션
슬랙에서 application-secret.properties 확인하고 추가하세요
=> [FEAT] 레디스 세팅

src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastStatisticsController.java, src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastStatistics.java, src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapper.java, src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsService.java, src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceImpl.java, src/main/resources/mappers/BroadcastStatisticsMapper.xml, src/test/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapperTest.java, src/test/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceTest.java
=> [FEAT] : 평균 시청자, 최고 시청자, 방송 진행 시간 업데이트 기능 추가, 방송 통계 객체에 조회수 필드 추가

.github/workflows/gradle.yml
=> [CHORE] 깃허브 워크플로우 yml 파일 레디스 설정 추가

src/main/java/susussg/pengreenlive/broadcast/controller/LiveRegisterController.java, src/main/java/susussg/pengreenlive/broadcast/dto/UpcomingBroadcastInfoDTO.java, src/main/java/susussg/pengreenlive/broadcast/mapper/LiveRegisterMapper.java, src/main/java/susussg/pengreenlive/broadcast/service/LiveRegisterService.java, src/main/java/susussg/pengreenlive/broadcast/service/LiveRegisterServiceImpl.java, src/main/resources/mappers/LiveRegisterMapper.xml, src/test/java/susussg/pengreenlive/mapper/LiveRegisterMapperTest.java, src/test/java/susussg/pengreenlive/service/MainServiceTest.java
- 방송 종료시 DB BRAODCAST_YN update 필요
=> [FEAT] 방송 예정 API 구현

.github/workflows/gradle.yml, build.gradle, src/main/java/susussg/pengreenlive/config/S3Config.java, src/main/java/susussg/pengreenlive/main/Controller/MainController.java, src/main/java/susussg/pengreenlive/util/Controller/S3Controller.java, src/main/java/susussg/pengreenlive/util/Service/ImageService.java, src/main/java/susussg/pengreenlive/util/Service/S3Service.java, src/main/resources/mappers/MainMapper.xml
- #관련 이슈 번호
- 프로퍼티 내용 슬랙 참고
- 사용방법 슬랙 참고
=> [FEAT] 슬라이드 수정 및 이미지 리사이징 및 S3 연동

src/main/java/susussg/pengreenlive/main/DTO/LiveChanceCarouselDTO.java, src/main/java/susussg/pengreenlive/main/DTO/MainCarouselDTO.java, src/main/java/susussg/pengreenlive/main/DTO/MainCarouselProductDTO.java, src/main/java/susussg/pengreenlive/main/DTO/ScheduledBroadcastDTO.java, src/main/resources/mappers/MainMapper.xml, src/test/java/susussg/pengreenlive/service/MainServiceTest.java
=> [FEAT] 메인화면 이미지 조회 로직 변경

src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java, src/main/java/susussg/pengreenlive/util/Service/ByteArrayMultipartFile.java, src/main/resources/mappers/ProductMapper.xml
=> [REFACTOR]  상품 등록, 수정 이미지 업로드 로직 변경

src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastStatisticsController.java, src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapper.java, src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsService.java, src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceImpl.java, src/main/resources/mappers/BroadcastStatisticsMapper.xml, src/test/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapperTest.java, src/test/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceTest.java
- #관련 이슈 번호
- CORS설정문제 떄문에 쿠키는 넣지 못했습니다.
=> [FEAT]: 누적 시청자 수 집계 기능 추가

src/main/java/susussg/pengreenlive/main/Controller/MainController.java, src/main/java/susussg/pengreenlive/main/DTO/LiveChanceCarouselDTO.java, src/main/resources/mappers/MainMapper.xml
=> [FIX] UUID 및 라이브 조회 오류 수정

src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastRegisterController.java, src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastDTO.java, src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastRegistrationRequestDTO.java, src/main/java/susussg/pengreenlive/broadcast/dto/PrepareBroadcastInfoDTO.java, src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastRegisterMapper.java, src/main/java/susussg/pengreenlive/broadcast/service/BroadcastRegisterService.java, src/main/java/susussg/pengreenlive/broadcast/service/BroadcastRegisterServiceImpl.java, src/main/resources/mappers/BroadcastRegisterMapper.xml, src/test/java/susussg/pengreenlive/mapper/LiveRegisterMapperTest.java, src/test/java/susussg/pengreenlive/service/MainServiceTest.java
=> [REFACTOR] 방송 등록하기 이미지 로직 변경

src/main/java/susussg/pengreenlive/statistics/controller/ProductStatisticsController.java, src/main/java/susussg/pengreenlive/statistics/dto/LabelInfo.java, src/main/java/susussg/pengreenlive/statistics/dto/ProductDetailsDTO.java, src/main/java/susussg/pengreenlive/statistics/dto/ProductInChannelDTO.java, src/main/java/susussg/pengreenlive/statistics/dto/SalesDataDTO.java, src/main/java/susussg/pengreenlive/statistics/mapper/ProductStatisticsMapper.java, src/main/java/susussg/pengreenlive/statistics/service/ProductStatisticsService.java, src/main/java/susussg/pengreenlive/statistics/service/ProductStatisticsServiceImpl.java, src/main/resources/mappers/ProductStatisticsMapper.xml
=> [FEAT] 상품 통계 API 작성

src/main/java/susussg/pengreenlive/config/RedisConfig.java, src/main/java/susussg/pengreenlive/payment/BrandPayController.java, src/main/java/susussg/pengreenlive/payment/PaymentController.java
=> [FEAT] 브랜드페이 api

src/main/java/susussg/pengreenlive/order/controller/ReviewController.java, src/main/java/susussg/pengreenlive/order/dto/ReviewDTO.java, src/main/java/susussg/pengreenlive/order/mapper/ReviewMapper.java, src/main/java/susussg/pengreenlive/order/service/ReviewService.java, src/main/java/susussg/pengreenlive/order/service/ReviewServiceImpl.java, src/main/resources/mappers/ReviewMapper.xml, src/test/java/susussg/pengreenlive/service/ProductServiceTest.java, src/test/java/susussg/pengreenlive/service/ReviewServiceTest.java, src/test/java/susussg/pengreenlive/service/ShopInfoServiceTest.java
=> [FEAT] 리뷰 확인 및 삭제 기능 구현

src/main/java/susussg/pengreenlive/order/controller/ReviewController.java, src/main/java/susussg/pengreenlive/order/dto/ReviewDTO.java, src/main/java/susussg/pengreenlive/order/mapper/ReviewMapper.java, src/main/java/susussg/pengreenlive/order/service/ReviewService.java, src/main/java/susussg/pengreenlive/order/service/ReviewServiceImpl.java, src/main/resources/mappers/ReviewMapper.xml, src/test/java/susussg/pengreenlive/service/ReviewServiceTest.java
=> [REFACTOR] 리뷰 등록 기능 수정

src/main/java/susussg/pengreenlive/broadcast/controller/WatchTimeController.java, src/main/java/susussg/pengreenlive/broadcast/dto/WatchTime.java, src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapper.java, src/main/java/susussg/pengreenlive/broadcast/mapper/WatchTimeMapper.java, src/main/java/susussg/pengreenlive/broadcast/service/WatchTimeService.java, src/main/java/susussg/pengreenlive/broadcast/service/WatchTimeServiceImpl.java, src/main/resources/mappers/BroadcastStatisticsMapper.xml, src/main/resources/mappers/WatchTimeMapper.xml
=> [FEAT] 평균시청시간 집계 기능 추가

src/main/java/susussg/pengreenlive/mypage/Controller/HistoryController.java, src/main/java/susussg/pengreenlive/mypage/DTO/HistoryDTO.java, src/main/java/susussg/pengreenlive/mypage/Mapper/HistoryMapper.java, src/main/java/susussg/pengreenlive/mypage/Service/HistoryService.java, src/main/java/susussg/pengreenlive/mypage/Service/HistoryServiceImpl.java, src/main/resources/mappers/HistoryMapper.xml, src/test/java/susussg/pengreenlive/service/HistoryServiceTest.java
=> [FEAT] 최근 본 방송 목록 조회

src/main/java/susussg/pengreenlive/broadcast/controller/ProductClickController.java, src/main/java/susussg/pengreenlive/broadcast/dto/ProductClick.java, src/main/java/susussg/pengreenlive/broadcast/mapper/ProductClicksMapper.java, src/main/java/susussg/pengreenlive/broadcast/service/ProductClickService.java, src/main/java/susussg/pengreenlive/broadcast/service/ProductClickServiceImpl.java, src/main/resources/mappers/ProductClicksMapper.xml
=> [FEAT] 상품 클릭 수 관련 기능 추가

src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java, src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastViewerCountController.java, src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastViewerCount.java, src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastViewerCountMapper.java, src/main/java/susussg/pengreenlive/broadcast/service/BroadcastViewerCountService.java, src/main/java/susussg/pengreenlive/broadcast/service/BroadcastViewerCountServiceImpl.java, src/main/java/susussg/pengreenlive/broadcast/service/WatchTimeServiceImpl.java, src/main/resources/mappers/BroadcastViewerCountMapper.xml
=> [FEAT] 시간대 별 시청자 수 집계 및 조회 기능 추가

src/main/java/susussg/pengreenlive/broadcast/controller/LiveBroadcastController.java, src/main/java/susussg/pengreenlive/broadcast/dto/LiveBroadcastProductDTO.java, src/main/java/susussg/pengreenlive/broadcast/mapper/LiveBroadcastMapper.java, src/main/java/susussg/pengreenlive/broadcast/service/LiveBroadcastService.java, src/main/java/susussg/pengreenlive/broadcast/service/LiveBroadcastServiceImpl.java, src/main/resources/mappers/LiveBroadcastMapper.xml, src/test/java/susussg/pengreenlive/mapper/LiveBroadcastProductMapperTest.java, src/test/java/susussg/pengreenlive/mapper/LiveRegisterMapperTest.java, src/test/java/susussg/pengreenlive/service/LiveBroadcastProductTest.java
=> [FEAT] 라이브 보드 방송 판매 상품 API 구현

src/main/java/susussg/pengreenlive/openai/controller/OpenAIController.java, src/main/java/susussg/pengreenlive/openai/service/OpenAIService.java
=> [FEAT] 상품 리뷰 유해성 검사

src/main/java/susussg/pengreenlive/naver/mapper/ReviewSummaryMapper.java, src/main/java/susussg/pengreenlive/naver/service/ReviewSummaryService.java, src/main/java/susussg/pengreenlive/naver/service/ReviewSummaryServiceImpl.java, src/main/resources/mappers/ReviewSummaryMapper.xml, src/test/java/susussg/pengreenlive/service/ReviewSummaryServiceTest.java
=> [FEAT] 리뷰 내용 문자열 출력

src/main/java/susussg/pengreenlive/statistics/controller/PythonController.java, src/main/java/susussg/pengreenlive/statistics/py/word_network.py, src/main/java/susussg/pengreenlive/statistics/service/PythonService.java, src/main/java/susussg/pengreenlive/statistics/service/PythonServiceImpl.java
=> [FEAT] 상품 시퀀스로 리뷰 의미망 분석

.github/workflows/gradle.yml, src/main/java/susussg/pengreenlive/statistics/dto/ProductDetailsDTO.java, src/main/java/susussg/pengreenlive/statistics/dto/ProductInChannelDTO.java, src/main/java/susussg/pengreenlive/statistics/py/word_network.py, src/main/java/susussg/pengreenlive/statistics/service/PythonServiceImpl.java, src/main/resources/mappers/ProductStatisticsMapper.xml
=> [FEAT] 분석 시 데이터 부족 예외 처리

src/main/java/susussg/pengreenlive/statistics/controller/PythonController.java, src/main/java/susussg/pengreenlive/statistics/py/word_network.py
=> [FIX] 메소드명 오류 수정

src/main/java/susussg/pengreenlive/chat/handler/BrokerController.java, src/main/java/susussg/pengreenlive/order/domain/Order.java, src/main/java/susussg/pengreenlive/order/util/UUIDConverter.java, src/main/java/susussg/pengreenlive/user/Mapper/UserMapper.java, src/main/java/susussg/pengreenlive/user/Service/UserService.java, src/main/java/susussg/pengreenlive/user/Service/UserServiceImpl.java, src/main/java/susussg/pengreenlive/user/controller/AccountController.java, src/main/java/susussg/pengreenlive/user/domain/LocalLogin.java, src/main/java/susussg/pengreenlive/user/domain/SocialLogin.java, src/main/java/susussg/pengreenlive/user/domain/TbUser.java, src/main/java/susussg/pengreenlive/user/dto/SignupFormDTO.java, src/main/java/susussg/pengreenlive/user/repository/UserRepository.java, src/main/java/susussg/pengreenlive/user/service/AccountService.java, src/main/resources/mappers/UserMapper.xml, src/test/java/susussg/pengreenlive/service/UserServiceTest.java, src/test/java/susussg/pengreenlive/user/service/AccountServiceTest.java
=> [FEAT] 일반회원가입 api

src/main/java/susussg/pengreenlive/statistics/py/word_network.py, src/main/java/susussg/pengreenlive/statistics/service/PythonServiceImpl.java
=> [FIX] 파이썬 로그 자바 콘솔에 표시

src/main/java/susussg/pengreenlive/naver/controller/ReviewSummaryController.java, src/main/java/susussg/pengreenlive/naver/service/ReviewSummaryService.java, src/main/java/susussg/pengreenlive/naver/service/ReviewSummaryServiceImpl.java
=> [FEAT] 상품별 리뷰 리스트 조회

src/main/java/susussg/pengreenlive/statistics/py/word_network.py, src/main/java/susussg/pengreenlive/statistics/service/PythonServiceImpl.java
=> [FIX] 로그 출력 수정

.github/workflows/gradle.yml, build.gradle, src/main/java/susussg/pengreenlive/config/RedisConfig.java, src/main/java/susussg/pengreenlive/payment/controller/BrandPayController.java, src/main/java/susussg/pengreenlive/payment/controller/PaymentController.java, src/main/java/susussg/pengreenlive/user/controller/AccountController.java, src/main/java/susussg/pengreenlive/user/service/AccountService.java, src/main/java/susussg/pengreenlive/user/util/SmsUtil.java, src/test/java/susussg/pengreenlive/user/service/AccountServiceTest.java
-  휴대폰 번호 인증 api
> slack 확인하시고 secret properties에 키 추가해주세요
=> [FEAT] 휴대폰 번호 인증 api

src/main/java/susussg/pengreenlive/naver/controller/SentimentReviewController.java, src/main/java/susussg/pengreenlive/naver/dto/SentimentRequestDTO.java, src/main/java/susussg/pengreenlive/naver/service/ReviewSummaryServiceImpl.java, src/main/java/susussg/pengreenlive/naver/service/SentimentService.java, src/main/java/susussg/pengreenlive/naver/service/SentimentServiceImpl.java
=> [FEAT] 리뷰 내용 감정 분석

src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java, src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastTimeDTO.java, src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastMapper.java, src/main/java/susussg/pengreenlive/broadcast/service/BroadcastService.java, src/main/java/susussg/pengreenlive/broadcast/service/BroadcastServiceImpl.java, src/main/resources/mappers/BroadcastMapper.xml, src/test/java/susussg/pengreenlive/mapper/BroadcastMapperTest.java
=> [FEAT] 방송 시작, 종료 시간 API 구현

src/main/java/susussg/pengreenlive/main/Controller/MainController.java, src/main/java/susussg/pengreenlive/main/DTO/SubscribedChannelDTO.java, src/main/java/susussg/pengreenlive/main/Mapper/MainMapper.java, src/main/java/susussg/pengreenlive/main/Service/MainService.java, src/main/java/susussg/pengreenlive/main/Service/MainServiceImpl.java, src/main/resources/mappers/MainMapper.xml
=> [FEAT] 유저 구독 목록 조회

src/main/java/susussg/pengreenlive/openapi/controller/GreenProductController.java, src/main/java/susussg/pengreenlive/openapi/service/GreenProductService.java
- #관련 이슈 번호
**서비스 메소드 내 주석 설명된 상태값 코드 반드시 확인 후 작업바랍니다.**
=> [FEAT] 녹색제품정보 OPEN API

src/main/java/susussg/pengreenlive/broadcast/controller/LiveBroadcastController.java, src/main/java/susussg/pengreenlive/broadcast/dto/LiveProductStatsDTO.java, src/main/java/susussg/pengreenlive/broadcast/mapper/LiveBroadcastMapper.java, src/main/java/susussg/pengreenlive/broadcast/service/LiveBroadcastService.java, src/main/java/susussg/pengreenlive/broadcast/service/LiveBroadcastServiceImpl.java, src/main/resources/mappers/LiveBroadcastMapper.xml
=> [FEAT] 실시간 방송 상품 상태 API 구현

src/main/java/susussg/pengreenlive/config/SecurityConfig.java, src/main/java/susussg/pengreenlive/login/dto/Member.java, src/main/java/susussg/pengreenlive/login/service/CustomAuthenticationFilter.java, src/main/java/susussg/pengreenlive/login/service/SecurityService.java, src/main/java/susussg/pengreenlive/main/Controller/MainController.java, src/main/java/susussg/pengreenlive/order/controller/OrderController.java, src/main/java/susussg/pengreenlive/order/controller/ReviewController.java, src/main/java/susussg/pengreenlive/order/mapper/ReviewMapper.java, src/main/java/susussg/pengreenlive/order/service/ReviewService.java, src/main/java/susussg/pengreenlive/order/service/ReviewServiceImpl.java, src/main/java/susussg/pengreenlive/payment/controller/BrandPayController.java, src/main/java/susussg/pengreenlive/user/Mapper/UserMapper.java, src/main/java/susussg/pengreenlive/user/Service/UserService.java, src/main/java/susussg/pengreenlive/user/Service/UserServiceImpl.java, src/main/java/susussg/pengreenlive/user/controller/UserController.java, src/main/resources/mappers/ReviewMapper.xml, src/main/resources/mappers/UserMapper.xml, src/test/java/susussg/pengreenlive/service/ReviewServiceTest.java
=> [TEST] 시큐리티 20% 적용 테스트

src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java, src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastStatisticsController.java, src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastViewerCountController.java, src/main/java/susussg/pengreenlive/broadcast/controller/LiveBroadcastController.java, src/main/java/susussg/pengreenlive/broadcast/controller/ProductClickController.java, src/main/java/susussg/pengreenlive/broadcast/controller/ProductReviewController.java, src/main/java/susussg/pengreenlive/dashboard/Controller/CategoryController.java, src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java, src/main/java/susussg/pengreenlive/dashboard/Controller/ShopInfoController.java, src/main/java/susussg/pengreenlive/main/Controller/MainController.java, src/main/java/susussg/pengreenlive/mypage/Controller/HistoryController.java, src/main/java/susussg/pengreenlive/naver/controller/ReviewSummaryController.java, src/main/java/susussg/pengreenlive/naver/controller/SentimentReviewController.java, src/main/java/susussg/pengreenlive/openai/controller/OpenAIController.java, src/main/java/susussg/pengreenlive/openapi/controller/GreenProductController.java, src/main/java/susussg/pengreenlive/order/controller/ReviewController.java, src/main/java/susussg/pengreenlive/statistics/controller/ProductStatisticsController.java, src/main/java/susussg/pengreenlive/test/Controller/TestController.java
=> [REFACTOR] API 엔드포인트 변경

src/main/java/susussg/pengreenlive/broadcast/controller/SubtitleController.java, src/main/java/susussg/pengreenlive/broadcast/dto/Subtitle.java, src/main/java/susussg/pengreenlive/chat/config/WebSockConfig.java
=> [FEAT] 실시간 자막 웹소켓 통신 기능 추가

src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java, src/main/java/susussg/pengreenlive/dashboard/DTO/GreenLabelDTO.java, src/main/java/susussg/pengreenlive/dashboard/DTO/ProductDTO.java, src/main/java/susussg/pengreenlive/dashboard/Mapper/ProductMapper.java, src/main/java/susussg/pengreenlive/dashboard/Service/ProductService.java, src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java, src/main/java/susussg/pengreenlive/util/Service/DateUtil.java, src/main/resources/mappers/ProductMapper.xml
=> [FEAT] 환경 인증 상품 등록 및 목록 조회 

src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java, src/main/java/susussg/pengreenlive/chat/handler/BrokerController.java, src/main/java/susussg/pengreenlive/util/Service/BanwordService.java
=> [FEAT] 금칙어 추가 로직

src/main/java/susussg/pengreenlive/mypage/Controller/HistoryController.java, src/main/java/susussg/pengreenlive/mypage/Mapper/HistoryMapper.java, src/main/java/susussg/pengreenlive/mypage/Service/HistoryService.java, src/main/java/susussg/pengreenlive/mypage/Service/HistoryServiceImpl.java, src/main/resources/mappers/HistoryMapper.xml
=> [FEAT] 방송 시청 기록 저장 API 구현

src/main/resources/mappers/BroadcastStatisticsMapper.xml
=> [FIX] 평균 구매 개수 쿼리문 수정

.github/workflows/gradle.yml, src/main/java/susussg/pengreenlive/broadcast/controller/OpenViduController.java, src/main/java/susussg/pengreenlive/config/CorsConfig.java, src/main/java/susussg/pengreenlive/config/RedisConfig.java, src/main/java/susussg/pengreenlive/config/SecurityConfig.java, src/main/java/susussg/pengreenlive/login/dto/Member.java, src/main/java/susussg/pengreenlive/login/service/CustomAuthenticationFilter.java, src/main/java/susussg/pengreenlive/login/service/CustomOncePerRequestFilter.java, src/main/java/susussg/pengreenlive/login/service/CustomUsernamePasswordAuthenticationTokenDeserializer.java, src/main/java/susussg/pengreenlive/login/service/SecurityService.java, src/main/java/susussg/pengreenlive/mypage/Controller/HistoryController.java, src/main/java/susussg/pengreenlive/order/controller/ReviewController.java, src/main/java/susussg/pengreenlive/order/mapper/ReviewMapper.java, src/main/java/susussg/pengreenlive/order/service/ReviewService.java, src/main/java/susussg/pengreenlive/order/service/ReviewServiceImpl.java, src/main/java/susussg/pengreenlive/user/Mapper/UserMapper.java, src/main/java/susussg/pengreenlive/user/Service/UserService.java, src/main/java/susussg/pengreenlive/user/Service/UserServiceImpl.java, src/main/java/susussg/pengreenlive/user/controller/UserController.java, src/main/java/susussg/pengreenlive/user/dto/UpdateUserFormDTO.java, src/main/resources/application.properties, src/main/resources/mappers/ReviewMapper.xml, src/main/resources/mappers/UserMapper.xml, src/test/java/susussg/pengreenlive/service/ReviewServiceTest.java
=> [FEAT] Cors 오류 수정 및 uuid 바인딩

src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java, src/main/java/susussg/pengreenlive/dashboard/DTO/ProductUpdateDTO.java, src/main/java/susussg/pengreenlive/dashboard/Mapper/ProductMapper.java, src/main/java/susussg/pengreenlive/dashboard/Service/ProductService.java, src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java, src/main/resources/mappers/ProductMapper.xml, src/test/java/susussg/pengreenlive/service/ProductServiceTest.java
=> [FIX] 상품 정보 수정 상품 이미지 null값 오류 수정

src/main/java/susussg/pengreenlive/config/SecurityConfig.java, src/main/java/susussg/pengreenlive/login/service/CustomAuthenticationFilter.java, src/main/java/susussg/pengreenlive/user/Service/UserServiceImpl.java, src/main/java/susussg/pengreenlive/user/controller/UserController.java, src/main/java/susussg/pengreenlive/user/dto/UpdateUserFormDTO.java, src/main/resources/mappers/UserMapper.xml
=> [FIX] Security cors 오류 수정

src/main/java/susussg/pengreenlive/login/service/CustomAuthenticationFilter.java, src/main/resources/application.properties
=> [feat] 프론트 url 수정

src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastStatisticsController.java, src/main/java/susussg/pengreenlive/broadcast/dto/LikeDTO.java, src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapper.java, src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsService.java, src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceImpl.java, src/main/resources/mappers/BroadcastStatisticsMapper.xml
- #관련 이슈 번호
- 새로운 테이블이 추가되었습니다. 노션에 업데이트하겠습니다.
=> [REFACTOR] 좋아요 중복 방지 추가 및 좋아요 정보 저장 테이블 추가

src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastDTO.java, src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastRegistrationRequestDTO.java, src/main/java/susussg/pengreenlive/broadcast/dto/ChannelSalesProductDTO.java
=> [FIX] 방송 DTO 데이터 타입 수정

build.gradle, src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java, src/main/java/susussg/pengreenlive/util/Controller/SwaggerConfig.java, src/main/resources/application.properties
- #관련 이슈 번호
- http://localhost:8090/swagger-ui/index.html Swagger 페이지 확인 가능 경로
- 각 메소드별로 @operation 어노테이션 추가하여 설명 작성해주시면 됩니다.
ex) @Operation(summary = "상품 등록", description = "녹색제품 ID를 인증하고 상품을 등록합니다.")
=> [FEAT] Swagger UI 추가

src/main/java/susussg/pengreenlive/config/SecurityConfig.java, src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java, src/main/java/susussg/pengreenlive/login/service/CustomAuthenticationFilter.java, src/main/java/susussg/pengreenlive/login/service/CustomOncePerRequestFilter.java, src/main/java/susussg/pengreenlive/login/service/CustomVendorAuthenticationFilter.java, src/main/java/susussg/pengreenlive/order/dto/BroadcastStockDTO.java, src/main/java/susussg/pengreenlive/order/dto/ProductStockDTO.java, src/main/java/susussg/pengreenlive/order/repository/BroadcastRepository.java, src/main/java/susussg/pengreenlive/order/repository/ProductStockRepository.java, src/main/java/susussg/pengreenlive/order/service/BroadcastScheduler.java, src/main/java/susussg/pengreenlive/order/service/OrderService.java, src/main/java/susussg/pengreenlive/order/service/ProductStockService.java, src/main/java/susussg/pengreenlive/payment/controller/BrandPayController.java, src/main/java/susussg/pengreenlive/user/controller/UserController.java, src/main/java/susussg/pengreenlive/vendor/controller/VendorAccountController.java, src/main/java/susussg/pengreenlive/vendor/controller/VendorController.java, src/main/java/susussg/pengreenlive/vendor/dto/VendorSignupFormDTO.java, src/main/java/susussg/pengreenlive/vendor/mapper/VendorMapper.java, src/main/java/susussg/pengreenlive/vendor/service/VendorAccountService.java, src/main/java/susussg/pengreenlive/vendor/service/VendorService.java, src/main/java/susussg/pengreenlive/vendor/service/VendorServiceImpl.java, src/main/resources/mappers/VendorMapper.xml
=> [feat] 브랜드페이 테스트

.github/workflows/gradle.yml, src/main/java/susussg/pengreenlive/vendor/controller/VendorAccountController.java, src/main/java/susussg/pengreenlive/vendor/service/VendorAccountService.java
=> [FEAT] 사업자 등록 인증 구현

src/main/java/susussg/pengreenlive/broadcast/dto/PrepareBroadcastInfoDTO.java, src/main/resources/mappers/BroadcastMapper.xml
=> [REFACTOR] 라이브 준비 전체 상품 보여주기 수정

src/main/java/susussg/pengreenlive/broadcast/dto/PrepareBroadcastInfoDTO.java
=> [FIX] 방송 에정 날짜 타입 변경

src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java, src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastStatisticsController.java, src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastDTO.java, src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastRegistrationRequestDTO.java, src/main/java/susussg/pengreenlive/broadcast/service/BroadcastServiceImpl.java, src/main/java/susussg/pengreenlive/config/SwaggerConfig.java, src/main/java/susussg/pengreenlive/login/service/CustomAuthenticationFilter.java, src/main/java/susussg/pengreenlive/order/domain/Broadcast.java, src/main/java/susussg/pengreenlive/order/domain/Order.java, src/main/java/susussg/pengreenlive/order/domain/Product.java, src/main/java/susussg/pengreenlive/user/Service/UserServiceImpl.java, src/main/java/susussg/pengreenlive/user/controller/AccountController.java, src/main/java/susussg/pengreenlive/user/controller/UserController.java, src/main/java/susussg/pengreenlive/user/dto/UpdateUserFormDTO.java, src/main/java/susussg/pengreenlive/user/util/SmsUtil.java, src/main/resources/mappers/BroadcastMapper.xml, src/main/resources/mappers/UserMapper.xml, src/test/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapperTest.java, src/test/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceTest.java
=> [test] 문자 발송 오류 로그

src/main/java/susussg/pengreenlive/broadcast/service/BroadcastServiceImpl.java, src/main/java/susussg/pengreenlive/order/controller/OrderController.java, src/main/java/susussg/pengreenlive/user/Service/UserServiceImpl.java
=> [FIX] 주문 오류, 방송 등록 오류 수정

src/main/java/susussg/pengreenlive/util/Service/S3Service.java, src/main/resources/mappers/MainMapper.xml
=> [FEAT] S3 설정 추가

.github/workflows/gradle.yml, src/main/java/susussg/pengreenlive/broadcast/controller/SubtitleController.java, src/main/java/susussg/pengreenlive/broadcast/dto/Subtitle.java, src/main/java/susussg/pengreenlive/broadcast/service/TranslationService.java, src/main/java/susussg/pengreenlive/broadcast/service/TranslationServiceImpl.java, src/test/java/susussg/pengreenlive/broadcast/service/TranslationServiceImplTest.java
=> [FEAT] 자막 번역 기능 추가

src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java, src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastStatisticsController.java, src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastViewerCountController.java, src/main/java/susussg/pengreenlive/broadcast/controller/OpenViduController.java, src/main/java/susussg/pengreenlive/broadcast/controller/ProductClickController.java, src/main/java/susussg/pengreenlive/broadcast/controller/SubtitleController.java, src/main/java/susussg/pengreenlive/broadcast/controller/WatchTimeController.java, src/main/java/susussg/pengreenlive/chat/config/WebSockConfig.java
=> [STYLE] Swagger API 설명 추가

src/main/java/susussg/pengreenlive/main/Controller/MainController.java, src/main/java/susussg/pengreenlive/openai/controller/OpenAIController.java, src/main/java/susussg/pengreenlive/order/controller/OrderController.java, src/main/java/susussg/pengreenlive/payment/controller/BrandPayController.java, src/main/java/susussg/pengreenlive/payment/controller/PaymentController.java, src/main/java/susussg/pengreenlive/user/controller/AccountController.java, src/main/java/susussg/pengreenlive/user/controller/UserController.java, src/main/java/susussg/pengreenlive/vendor/controller/VendorAccountController.java
=> [FEAT] 스웨거 등록

src/main/java/susussg/pengreenlive/chat/controller/ChatController.java, src/main/java/susussg/pengreenlive/chat/controller/ChatRoomController.java, src/main/java/susussg/pengreenlive/chat/controller/RoomController.java, src/main/java/susussg/pengreenlive/openai/controller/OpenAIController.java, src/main/java/susussg/pengreenlive/openapi/controller/GreenProductController.java, src/main/java/susussg/pengreenlive/statistics/controller/PythonController.java, src/main/java/susussg/pengreenlive/util/Controller/S3Controller.java
=> [STYLE] Swagger 어노테이션 설명 추가

src/main/java/susussg/pengreenlive/user/Service/UserServiceImpl.java, src/main/resources/mappers/VendorMapper.xml
=> [FEAT] 프로필 이미지 압축률 수정
